export const MAKE_REQUEST_ASYNC_SAGAS = 'MAKE_REQUEST_ASYNC_SAGAS';
export const MAKE_REQUEST_SUCCESS_SAGAS = 'MAKE_REQUEST_SUCCESS_SAGAS';
export const MAKE_REQUEST_FAILED_SAGAS = 'MAKE_REQUEST_FAILED_SAGAS';
export const MAKE_REQUEST_ASYNC_THUNK = 'MAKE_REQUEST_ASYNC_THUNK';
export const MAKE_REQUEST_SUCCESS_THUNK = 'MAKE_REQUEST_SUCCESS_THUNK';
export const MAKE_REQUEST_FAILED_THUNK = 'MAKE_REQUEST_FAILED_THUNK';
